title: WildFly Proposals
url: "https://docs.wildfly.org/"
baseurl: /wildfly-proposals
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
sass:
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: "proposal"

collections:
  docs:
    output: true
  wildfly-categories:
    output: true

asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    imagesdir: /assets/img/news/